version: '3.7'

services:
  #MySql Service
  mysql:
    image: mysql:latest
    container_name: dbserver
    restart: always

    ports:
      - "3306:3306"

    environment:
      MYSQL_DATABASE: guard
      MYSQL_ROOT_PASSWORD: password

    volumes:
      - /var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

  # PHP-FPM Service
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: app
    restart: always
    working_dir: /var/www

    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  # NGINX Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
